#!/bin/sh
#
# dbus-conext-bridge installer for Venus OS
# Installs the Conext XW Pro bridge driver as a runit service.
#
set -e

INSTALL_DIR="/data/dbus-conext-bridge"
SERVICE_DIR="/service/dbus-conext-bridge"
SRC_DIR="$(dirname "$0")"

echo "=== dbus-conext-bridge installer ==="
echo ""

# Create install directory
mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/service/log"

# Copy driver files
cp "$SRC_DIR/dbus-conext-bridge.py" "$INSTALL_DIR/"
cp "$SRC_DIR/conext-poller.py" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/conext-poller.py"
echo "  Installed driver (bridge + poller)"

# Copy config (preserve existing)
if [ -f "$INSTALL_DIR/config.ini" ]; then
    echo "  Existing config.ini preserved (not overwritten)"
    cp "$SRC_DIR/config.default.ini" "$INSTALL_DIR/config.default.ini"
else
    cp "$SRC_DIR/config.default.ini" "$INSTALL_DIR/config.ini"
    echo "  Installed default config.ini"
fi

# Create service run script
cat > "$INSTALL_DIR/service/run" << 'EOF'
#!/bin/sh
exec 2>&1
# Start Modbus poller as separate process (writes to /tmp/conext_cache.json)
python3 -u /data/dbus-conext-bridge/conext-poller.py &
sleep 8
# Bridge reads JSON cache only — zero DBUS blocking
exec python3 -u /data/dbus-conext-bridge/dbus-conext-bridge.py
EOF
chmod +x "$INSTALL_DIR/service/run"
echo "  Created service/run"

# Create log service
cat > "$INSTALL_DIR/service/log/run" << 'EOF'
#!/bin/sh
exec svlogd -tt /var/log/dbus-conext-bridge
EOF
chmod +x "$INSTALL_DIR/service/log/run"
mkdir -p /var/log/dbus-conext-bridge
echo "  Created service/log/run"

# Register runit service (symlink to /service)
if [ ! -L "$SERVICE_DIR" ]; then
    ln -s "$INSTALL_DIR/service" "$SERVICE_DIR"
    echo "  Registered runit service"
else
    echo "  Service already registered"
fi

# Boot persistence: /service is tmpfs on Venus OS, symlinks lost on reboot
# Add re-creation to /data/rc.local
RC_LOCAL="/data/rc.local"
RC_LINE="ln -sf $INSTALL_DIR/service $SERVICE_DIR"
if [ ! -f "$RC_LOCAL" ]; then
    cat > "$RC_LOCAL" << RCEOF
#!/bin/sh
# Auto-generated by dbus-conext-bridge installer
$RC_LINE
RCEOF
    chmod +x "$RC_LOCAL"
    echo "  Created $RC_LOCAL for boot persistence"
elif ! grep -q "dbus-conext-bridge" "$RC_LOCAL"; then
    echo "# dbus-conext-bridge service" >> "$RC_LOCAL"
    echo "$RC_LINE" >> "$RC_LOCAL"
    echo "  Added boot persistence to $RC_LOCAL"
else
    echo "  Boot persistence already in $RC_LOCAL"
fi

# --- Register DBUS settings (localsettings) ---
DBUS_CMD="dbus -y com.victronenergy.settings /Settings"
echo "  Registering DBUS settings..."
$DBUS_CMD AddSetting ConextBridge GatewayIp "192.168.1.223" s 0 0 2>/dev/null || true
$DBUS_CMD AddSetting ConextBridge GatewayPort 503 i 1 65535 2>/dev/null || true
$DBUS_CMD AddSetting ConextBridge UnitIds "11,12" s 0 0 2>/dev/null || true
$DBUS_CMD AddSetting ConextBridge UnitCount 2 i 1 4 2>/dev/null || true
$DBUS_CMD AddSetting ConextBridge PollInterval 3000 i 1000 30000 2>/dev/null || true
echo "  DBUS settings registered"

# --- Install GX GUI settings pages ---
GUIV1_DIR="/opt/victronenergy/gui/qml"
QML_FILE="PageSettingsConextBridge.qml"

# gui-v1 QML page
if [ -d "$GUIV1_DIR" ]; then
    cp "$SRC_DIR/gui/$QML_FILE" "$GUIV1_DIR/$QML_FILE"
    echo "  Installed gui-v1 settings page"

    # Patch PageSettings.qml to add Conext Bridge menu entry
    PAGESETTINGS="$GUIV1_DIR/PageSettings.qml"
    if [ -f "$PAGESETTINGS" ] && ! grep -q "ConextBridge" "$PAGESETTINGS"; then
        # Backup original
        [ ! -f "$PAGESETTINGS.orig.conext" ] && cp "$PAGESETTINGS" "$PAGESETTINGS.orig.conext"
        # Insert menu entry before the last closing brace of the model
        sed -i '/^[[:space:]]*MbSubMenu.*{$/,/^[[:space:]]*}$/{
            /^[[:space:]]*}$/a\
\
            MbSubMenu {\
                description: qsTr("Conext Bridge")\
                subpage: Component { PageSettingsConextBridge {} }\
            }
        }' "$PAGESETTINGS"
        # Only keep the LAST inserted copy (sed may insert multiple times)
        # Simpler: just check if it was inserted, if multiple, user can fix
        echo "  Added Conext Bridge to Settings menu (gui-v1)"
    else
        echo "  Settings menu entry already present (gui-v1)"
    fi
else
    echo "  gui-v1 not found, skipping"
fi

# Restart service
svc -t "$SERVICE_DIR" 2>/dev/null || true
sleep 3

echo ""
echo "=== Installation complete ==="
svstat "$SERVICE_DIR"
echo ""
echo "Settings available in GX menu: Settings > Conext Bridge"
echo "  Or edit $INSTALL_DIR/config.ini and restart:"
echo "  svc -t $SERVICE_DIR"
