#!/bin/sh
#
# dbus-conext-bridge installer for Venus OS
# Installs the Conext XW Pro bridge driver as a runit service.
#
set -e

INSTALL_DIR="/data/dbus-conext-bridge"
SERVICE_DIR="/service/dbus-conext-bridge"
SRC_DIR="$(dirname "$0")"

echo "=== dbus-conext-bridge installer ==="
echo ""

# Create install directory
mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/service/log"

# Copy driver files
cp "$SRC_DIR/dbus-conext-bridge.py" "$INSTALL_DIR/"
cp "$SRC_DIR/conext-poller.py" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/conext-poller.py"
echo "  Installed driver (bridge + poller)"

# Copy config (preserve existing)
if [ -f "$INSTALL_DIR/config.ini" ]; then
    echo "  Existing config.ini preserved (not overwritten)"
    cp "$SRC_DIR/config.default.ini" "$INSTALL_DIR/config.default.ini"
else
    cp "$SRC_DIR/config.default.ini" "$INSTALL_DIR/config.ini"
    echo "  Installed default config.ini"
fi

# Create service run script
cat > "$INSTALL_DIR/service/run" << 'EOF'
#!/bin/sh
exec 2>&1
# Start Modbus poller as separate process (writes to /tmp/conext_cache.json)
python3 -u /data/dbus-conext-bridge/conext-poller.py &
sleep 3
# Bridge reads JSON cache only — zero DBUS blocking
exec python3 -u /data/dbus-conext-bridge/dbus-conext-bridge.py
EOF
chmod +x "$INSTALL_DIR/service/run"
echo "  Created service/run"

# Create log service
cat > "$INSTALL_DIR/service/log/run" << 'EOF'
#!/bin/sh
exec svlogd -tt /var/log/dbus-conext-bridge
EOF
chmod +x "$INSTALL_DIR/service/log/run"
mkdir -p /var/log/dbus-conext-bridge
echo "  Created service/log/run"

# Register runit service (symlink to /service)
if [ ! -L "$SERVICE_DIR" ]; then
    ln -s "$INSTALL_DIR/service" "$SERVICE_DIR"
    echo "  Registered runit service"
else
    echo "  Service already registered"
fi

# Boot persistence: /service is tmpfs on Venus OS, symlinks lost on reboot
# Add re-creation to /data/rc.local
RC_LOCAL="/data/rc.local"
RC_LINE="ln -sf $INSTALL_DIR/service $SERVICE_DIR"
if [ ! -f "$RC_LOCAL" ]; then
    cat > "$RC_LOCAL" << RCEOF
#!/bin/sh
# Auto-generated by dbus-conext-bridge installer
$RC_LINE
RCEOF
    chmod +x "$RC_LOCAL"
    echo "  Created $RC_LOCAL for boot persistence"
elif ! grep -q "dbus-conext-bridge" "$RC_LOCAL"; then
    echo "# dbus-conext-bridge service" >> "$RC_LOCAL"
    echo "$RC_LINE" >> "$RC_LOCAL"
    echo "  Added boot persistence to $RC_LOCAL"
else
    echo "  Boot persistence already in $RC_LOCAL"
fi

# Restart service
svc -t "$SERVICE_DIR" 2>/dev/null || true
sleep 3

echo ""
echo "=== Installation complete ==="
svstat "$SERVICE_DIR"
echo ""
echo "Edit $INSTALL_DIR/config.ini to configure:"
echo "  - Gateway IP address"
echo "  - Inverter unit IDs"
echo "  - Number of inverters"
echo ""
echo "Restart after config change: svc -t $SERVICE_DIR"
